/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cs10finalproject;

import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author 44869
 */
public class Battleship_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Setting_GUI
     */
    Battleship_game b;
    Start s = new Start();
    JLabel[][] labels, labelsB;
    JLabel[] numbers, letters, lettersB, numbersB;
    ImageIcon[][] boardA = new ImageIcon[10][10];
    String[] letter = {"A", "B", "C", "D", "E", "F", "G", "H", "I", "J"}, l = {"a", "b", "c", "d", "e", "f", "g", "h", "i", "j"};

    public Battleship_GUI() {
        initComponents();
        b = new Battleship_game();
        b.setImage();
        b.setEmpty();
        Bombing.setVisible(false);
        Result.setVisible(false);
        lblNumRound.setText(String.valueOf(b.roundsRemain));

        numbers = new JLabel[10];
        for (int i = 0; i < numbers.length; i++) {
            numbers[i] = new JLabel();
            numbers[i].setVisible(true);
            numbers[i].setSize(28, 28);
            numbers[i].setLocation(28, (i + 1) * 28);
            numbers[i].setText(String.valueOf(i + 1));
            Setting.add(numbers[i]);

        }
        letters = new JLabel[10];
        for (int i = 0; i < letters.length; i++) {
            letters[i] = new JLabel();
            letters[i].setVisible(true);
            letters[i].setSize(28, 28);
            letters[i].setLocation((i + 2) * 28 + 10, 0);
            letters[i].setText(letter[i]);
            Setting.add(letters[i]);
        }
        labels = new JLabel[10][10];
        for (int i = 0; i < labels.length; i++) {
            for (int q = 0; q < labels.length; q++) {
                labels[i][q] = new JLabel();
                labels[i][q].setVisible(true);
                labels[i][q].setSize(28, 28);
                labels[i][q].setLocation((i + 1) * 28 + 28, (q + 1) * 28 + 5);
                labels[i][q].setIcon(b.set[i][q]);
                Setting.add(labels[i][q]);
            }
        }

        lblR1.setText(String.valueOf(b.remain[1]));
        lblR2.setText(String.valueOf(b.remain[2]));
        lblR3.setText(String.valueOf(b.remain[3]));
        lblR4.setText(String.valueOf(b.remain[4]));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        Setting = new javax.swing.JPanel();
        lblX = new javax.swing.JLabel();
        lblY = new javax.swing.JLabel();
        txtEnterX = new javax.swing.JTextField();
        txtEnterY = new javax.swing.JTextField();
        btnBattle = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        cobDirection = new javax.swing.JComboBox<>();
        btnEnter = new javax.swing.JButton();
        cobType = new javax.swing.JComboBox<>();
        btnClear = new javax.swing.JButton();
        lblRemain = new javax.swing.JLabel();
        lblR1 = new javax.swing.JLabel();
        lblR2 = new javax.swing.JLabel();
        lblR3 = new javax.swing.JLabel();
        lblR4 = new javax.swing.JLabel();
        lblRange = new javax.swing.JLabel();
        btnRandom = new javax.swing.JButton();
        Bombing = new javax.swing.JPanel();
        lblTitleA = new javax.swing.JLabel();
        lblBX = new javax.swing.JLabel();
        txtBX = new javax.swing.JTextField();
        txtBY = new javax.swing.JTextField();
        lblBY = new javax.swing.JLabel();
        lblTitleB = new javax.swing.JLabel();
        lblPointA = new javax.swing.JLabel();
        lblPointB = new javax.swing.JLabel();
        btnBomb = new javax.swing.JButton();
        lblBombingResultA = new javax.swing.JLabel();
        lblBombingResultB = new javax.swing.JLabel();
        lblRound = new javax.swing.JLabel();
        lblNumRound = new javax.swing.JLabel();
        Result = new javax.swing.JPanel();
        lblTitleScoreA = new javax.swing.JLabel();
        lblFinalScoreA = new javax.swing.JLabel();
        lblTitleScoreB = new javax.swing.JLabel();
        lblFinalScoreB = new javax.swing.JLabel();
        lblWinner = new javax.swing.JLabel();
        btnBackToMenu2 = new javax.swing.JButton();
        btnQuit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Setting.setBackground(new java.awt.Color(204, 204, 255));
        Setting.setPreferredSize(new java.awt.Dimension(731, 502));

        lblX.setText("Enter x coordinate");

        lblY.setText("Enter y coordinate");

        btnBattle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs10finalproject/images/BattleButton.gif"))); // NOI18N
        btnBattle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBattleActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs10finalproject/images/1.jpg"))); // NOI18N

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs10finalproject/images/2.jpg"))); // NOI18N

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs10finalproject/images/3.jpg"))); // NOI18N

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs10finalproject/images/4.jpg"))); // NOI18N

        cobDirection.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Direction", "North", "South", "East", "West" }));
        cobDirection.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobDirectionActionPerformed(evt);
            }
        });

        btnEnter.setText("Enter");
        btnEnter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnterActionPerformed(evt);
            }
        });

        cobType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ship Type", "A", "B", "C", "D" }));
        cobType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cobTypeActionPerformed(evt);
            }
        });

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });

        lblRemain.setText("Remain");

        lblR1.setBackground(new java.awt.Color(204, 204, 255));
        lblR1.setOpaque(true);

        lblR2.setBackground(new java.awt.Color(204, 204, 255));
        lblR2.setOpaque(true);

        lblR3.setBackground(new java.awt.Color(204, 204, 255));
        lblR3.setOpaque(true);

        lblR4.setBackground(new java.awt.Color(204, 204, 255));
        lblR4.setOpaque(true);

        lblRange.setBackground(new java.awt.Color(204, 204, 255));
        lblRange.setOpaque(true);

        btnRandom.setText("Random setting");
        btnRandom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRandomActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout SettingLayout = new javax.swing.GroupLayout(Setting);
        Setting.setLayout(SettingLayout);
        SettingLayout.setHorizontalGroup(
            SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingLayout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingLayout.createSequentialGroup()
                        .addComponent(cobDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(62, 62, 62)
                        .addComponent(cobType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(SettingLayout.createSequentialGroup()
                        .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SettingLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(lblRange, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(SettingLayout.createSequentialGroup()
                                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(SettingLayout.createSequentialGroup()
                                        .addComponent(lblY)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEnterY, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(SettingLayout.createSequentialGroup()
                                        .addComponent(lblX)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtEnterX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(SettingLayout.createSequentialGroup()
                                        .addComponent(btnEnter)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnClear))
                                    .addComponent(btnRandom, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnBattle)
                        .addContainerGap(81, Short.MAX_VALUE))))
            .addGroup(SettingLayout.createSequentialGroup()
                .addGap(446, 446, 446)
                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel4)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addGap(33, 33, 33)
                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblR4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRemain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblR1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblR2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblR3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        SettingLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtEnterX, txtEnterY});

        SettingLayout.setVerticalGroup(
            SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SettingLayout.createSequentialGroup()
                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingLayout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblR1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lblR2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(lblR3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(lblR4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(SettingLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblRemain)))
                .addGap(80, 80, 80)
                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cobDirection, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cobType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(SettingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblRange, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(SettingLayout.createSequentialGroup()
                                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblX)
                                    .addComponent(txtEnterX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblY)
                                    .addComponent(txtEnterY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(SettingLayout.createSequentialGroup()
                                .addGroup(SettingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEnter)
                                    .addComponent(btnClear))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRandom)))
                        .addGap(46, 46, 46))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, SettingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                        .addComponent(btnBattle)
                        .addGap(34, 34, 34))))
        );

        Bombing.setBackground(new java.awt.Color(204, 204, 255));
        Bombing.setPreferredSize(new java.awt.Dimension(731, 502));

        lblTitleA.setText("Your Board");

        lblBX.setText("Enter x coordinate");

        txtBX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBXActionPerformed(evt);
            }
        });

        lblBY.setText("Enter y coordinate");

        lblTitleB.setText("Computer's Board");

        lblPointA.setText("0");

        lblPointB.setText("0");

        btnBomb.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cs10finalproject/images/Bomb Logo.png"))); // NOI18N
        btnBomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBombActionPerformed(evt);
            }
        });

        lblBombingResultA.setBackground(new java.awt.Color(204, 204, 255));
        lblBombingResultA.setOpaque(true);

        lblBombingResultB.setBackground(new java.awt.Color(204, 204, 255));
        lblBombingResultB.setOpaque(true);

        lblRound.setText("Rounds Remain");

        lblNumRound.setBackground(new java.awt.Color(204, 204, 255));
        lblNumRound.setOpaque(true);

        javax.swing.GroupLayout BombingLayout = new javax.swing.GroupLayout(Bombing);
        Bombing.setLayout(BombingLayout);
        BombingLayout.setHorizontalGroup(
            BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BombingLayout.createSequentialGroup()
                .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BombingLayout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(lblTitleA))
                    .addGroup(BombingLayout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addComponent(lblPointA)))
                .addGap(99, 99, 99)
                .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRound)
                    .addComponent(lblNumRound, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BombingLayout.createSequentialGroup()
                        .addComponent(lblTitleB)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BombingLayout.createSequentialGroup()
                        .addComponent(lblPointB)
                        .addGap(167, 167, 167))))
            .addGroup(BombingLayout.createSequentialGroup()
                .addGap(147, 147, 147)
                .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BombingLayout.createSequentialGroup()
                        .addComponent(lblBX)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(BombingLayout.createSequentialGroup()
                        .addComponent(lblBY)
                        .addGap(7, 7, 7)))
                .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtBY)
                    .addComponent(txtBX, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(55, 55, 55)
                .addComponent(btnBomb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblBombingResultB, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblBombingResultA, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        BombingLayout.setVerticalGroup(
            BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BombingLayout.createSequentialGroup()
                .addContainerGap(345, Short.MAX_VALUE)
                .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblTitleA, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblRound))
                    .addComponent(lblTitleB, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPointA, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPointB, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblNumRound, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BombingLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBX, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBX))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtBY, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblBY))
                        .addGap(24, 24, 24))
                    .addGroup(BombingLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(BombingLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BombingLayout.createSequentialGroup()
                                .addComponent(lblBombingResultA, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblBombingResultB, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnBomb))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        Result.setBackground(new java.awt.Color(204, 204, 255));
        Result.setPreferredSize(new java.awt.Dimension(731, 502));

        lblTitleScoreA.setText("Your Score");

        lblFinalScoreA.setBackground(new java.awt.Color(204, 204, 255));
        lblFinalScoreA.setOpaque(true);

        lblTitleScoreB.setText("Your Opponent's Score");

        lblFinalScoreB.setBackground(new java.awt.Color(204, 204, 255));
        lblFinalScoreB.setOpaque(true);

        lblWinner.setBackground(new java.awt.Color(204, 204, 255));
        lblWinner.setOpaque(true);

        btnBackToMenu2.setText("Back To Menu");
        btnBackToMenu2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackToMenu2ActionPerformed(evt);
            }
        });

        btnQuit.setText("Quit");
        btnQuit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnQuitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout ResultLayout = new javax.swing.GroupLayout(Result);
        Result.setLayout(ResultLayout);
        ResultLayout.setHorizontalGroup(
            ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ResultLayout.createSequentialGroup()
                .addContainerGap(182, Short.MAX_VALUE)
                .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblTitleScoreA, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblFinalScoreA, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(157, 157, 157)
                .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblTitleScoreB)
                    .addComponent(lblFinalScoreB, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(182, 182, 182))
            .addGroup(ResultLayout.createSequentialGroup()
                .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ResultLayout.createSequentialGroup()
                        .addGap(248, 248, 248)
                        .addComponent(lblWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ResultLayout.createSequentialGroup()
                        .addGap(270, 270, 270)
                        .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnBackToMenu2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnQuit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        ResultLayout.setVerticalGroup(
            ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ResultLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitleScoreA)
                    .addComponent(lblTitleScoreB))
                .addGap(18, 18, 18)
                .addGroup(ResultLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFinalScoreA, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblFinalScoreB, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 135, Short.MAX_VALUE)
                .addComponent(lblWinner, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBackToMenu2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnQuit)
                .addGap(67, 67, 67))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Setting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Bombing, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Result, javax.swing.GroupLayout.PREFERRED_SIZE, 498, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(Bombing, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
                        .addComponent(Setting, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBattleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBattleActionPerformed
        // TODO add your handling code here:
        if (b.remain[1] == 0 && b.remain[2] == 0 && b.remain[3] == 0 && b.remain[4] == 0) {
            b.remain[1] = 1;
            b.remain[2] = 2;
            b.remain[3] = 3;
            b.remain[4] = 4;
            Bombing.setVisible(true);
            Setting.setVisible(false);
            for (int i = 0; i < labels.length; i++) {
                for (int q = 0; q < labels.length; q++) {
                    Bombing.add(labels[i][q]);
                }
                Bombing.add(numbers[i]);
                Bombing.add(letters[i]);
            }
            numbersB = new JLabel[10];
            for (int i = 0; i < numbers.length; i++) {
                numbersB[i] = new JLabel();
                numbersB[i].setVisible(true);
                numbersB[i].setSize(28, 28);
                numbersB[i].setLocation(28 + 350, (i + 1) * 28);
                numbersB[i].setText(String.valueOf(i + 1));
                Bombing.add(numbersB[i]);

            }
            lettersB = new JLabel[10];
            for (int i = 0; i < lettersB.length; i++) {
                lettersB[i] = new JLabel();
                lettersB[i].setVisible(true);
                lettersB[i].setSize(28, 28);
                lettersB[i].setLocation((i + 2) * 28 + 360, 0);
                lettersB[i].setText(letter[i]);
                Bombing.add(lettersB[i]);
            }
            b.FinishSetting();
            b.setEmpty();
            b.setRandom();
            b.setComputer();
            labelsB = new JLabel[10][10];
            for (int i = 0; i < labelsB.length; i++) {
                for (int q = 0; q < labelsB.length; q++) {
                    labelsB[i][q] = new JLabel();
                    labelsB[i][q].setVisible(true);
                    labelsB[i][q].setSize(28, 28);
                    labelsB[i][q].setLocation((i + 1) * 28 + 428 - 50, (q + 1) * 28 + 5);
                    labelsB[i][q].setIcon(b.ic[0]);
                    Bombing.add(labelsB[i][q]);
                }
            }
        } else {
            lblRange.setText("Please finish your setting.");
        }
    }//GEN-LAST:event_btnBattleActionPerformed

    private void btnEnterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnterActionPerformed
        // TODO add your handling code here:
        int ln = 0;
        for (int i = 0; i < 10; i++) {
            if (!l[ln].equals(txtEnterX.getText()) && !letter[ln].equals(txtEnterX.getText())) {
                ln++;
            }
        }
        b.setX(ln);
        b.setY((int) Double.parseDouble(txtEnterY.getText()) - 1);
        b.type = cobType.getSelectedIndex();
        b.setShipHead();
        b.direction = cobDirection.getSelectedIndex();
        b.setShipBody();

        for (int i = 0; i < labels.length; i++) {
            for (int q = 0; q < labels.length; q++) {
                labels[i][q].setIcon(b.set[i][q]);
            }
        }
        lblRange.setText(b.outRange);

        cobDirection.setSelectedIndex(0);
        cobType.setSelectedIndex(0);
        txtEnterX.setText("");
        txtEnterY.setText("");
        lblR1.setText(String.valueOf(b.remain[1]));
        lblR2.setText(String.valueOf(b.remain[2]));
        lblR3.setText(String.valueOf(b.remain[3]));
        lblR4.setText(String.valueOf(b.remain[4]));
    }//GEN-LAST:event_btnEnterActionPerformed

    private void cobDirectionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobDirectionActionPerformed
        // TODO add your handling code here:
        b.direction = cobDirection.getSelectedIndex();
    }//GEN-LAST:event_cobDirectionActionPerformed

    private void cobTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cobTypeActionPerformed
        // TODO add your handling code here:
        b.type = cobType.getSelectedIndex();
    }//GEN-LAST:event_cobTypeActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        // TODO add your handling code here:
        b.setEmpty();
        for (int i = 0; i < labels.length; i++) {
            for (int q = 0; q < labels.length; q++) {
                labels[i][q].setIcon(b.set[i][q]);
            }
        }
        b.remain[1] = 1;
        b.remain[2] = 2;
        b.remain[3] = 3;
        b.remain[4] = 4;
        lblR1.setText(String.valueOf(b.remain[1]));
        lblR2.setText(String.valueOf(b.remain[2]));
        lblR3.setText(String.valueOf(b.remain[3]));
        lblR4.setText(String.valueOf(b.remain[4]));
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnBombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBombActionPerformed
        // TODO add your handling code here:
        if (b.roundsRemain != 0) {
            int ln = 0;
            while (!(l[ln].equals(txtBX.getText()) || letter[ln].equals(txtBX.getText()))) {
                ln++;
            }
            b.x = ln;
            b.y = (int) Double.parseDouble(txtBY.getText()) - 1;
            b.setBombing();
            labelsB[b.x][b.y].setIcon(b.set[b.x][b.y]);
            b.setComputerBombing();
            for (int i = 0; i < labels.length; i++) {
                for (int q = 0; q < labels.length; q++) {
                    labels[i][q].setIcon(b.set_[i][q]);
                }
            }
            lblBombingResultA.setText(b.resultA);
            lblBombingResultB.setText(b.resultB);
            if (b.roundsRemain > 0) {
                lblNumRound.setText(String.valueOf(b.roundsRemain));
            } else {
                lblNumRound.setText("No rounds remain");
            }
            lblPointA.setText(String.valueOf(b.pointA));
            lblPointB.setText(String.valueOf(b.pointB));
            txtBX.setText("");
            txtBY.setText("");

            if (b.roundsRemain == 0) {
                btnBomb.setIcon(b.ic[9]);
            }
        } else {
            Result.setVisible(true);
            Bombing.setVisible(false);
            lblFinalScoreA.setText(String.valueOf(b.pointA));
            lblFinalScoreB.setText(String.valueOf(b.pointB));
            b.PrintResult();
            lblWinner.setText(b.finalResult);
        }
    }//GEN-LAST:event_btnBombActionPerformed
    /**/
    private void txtBXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBXActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBXActionPerformed

    private void btnBackToMenu2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackToMenu2ActionPerformed
        // TODO add your handling code here:
        s.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBackToMenu2ActionPerformed

    private void btnQuitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnQuitActionPerformed
        // TODO add your handling code here:
        this.dispose();
        s.dispose();
    }//GEN-LAST:event_btnQuitActionPerformed

    private void btnRandomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRandomActionPerformed
        // TODO add your handling code here:
        b.setRandom();
        b.setComputer();
        for (int i = 0; i < labels.length; i++) {
            for (int q = 0; q < labels.length; q++) {
                labels[i][q].setIcon(b.set[i][q]);
            }
        }
        for (int i = 1; i <= 4; i++) {
            b.remain[i] = 0;
        }
        lblR1.setText(String.valueOf(b.remain[1]));
        lblR2.setText(String.valueOf(b.remain[2]));
        lblR3.setText(String.valueOf(b.remain[3]));
        lblR4.setText(String.valueOf(b.remain[4]));
    }//GEN-LAST:event_btnRandomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Battleship_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Battleship_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Battleship_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Battleship_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Battleship_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Bombing;
    private javax.swing.JPanel Result;
    private javax.swing.JPanel Setting;
    private javax.swing.JButton btnBackToMenu2;
    private javax.swing.JButton btnBattle;
    private javax.swing.JButton btnBomb;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnEnter;
    private javax.swing.JButton btnQuit;
    private javax.swing.JButton btnRandom;
    private javax.swing.JComboBox<String> cobDirection;
    private javax.swing.JComboBox<String> cobType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel lblBX;
    private javax.swing.JLabel lblBY;
    private javax.swing.JLabel lblBombingResultA;
    private javax.swing.JLabel lblBombingResultB;
    private javax.swing.JLabel lblFinalScoreA;
    private javax.swing.JLabel lblFinalScoreB;
    private javax.swing.JLabel lblNumRound;
    private javax.swing.JLabel lblPointA;
    private javax.swing.JLabel lblPointB;
    private javax.swing.JLabel lblR1;
    private javax.swing.JLabel lblR2;
    private javax.swing.JLabel lblR3;
    private javax.swing.JLabel lblR4;
    private javax.swing.JLabel lblRange;
    private javax.swing.JLabel lblRemain;
    private javax.swing.JLabel lblRound;
    private javax.swing.JLabel lblTitleA;
    private javax.swing.JLabel lblTitleB;
    private javax.swing.JLabel lblTitleScoreA;
    private javax.swing.JLabel lblTitleScoreB;
    private javax.swing.JLabel lblWinner;
    private javax.swing.JLabel lblX;
    private javax.swing.JLabel lblY;
    private javax.swing.JTextField txtBX;
    private javax.swing.JTextField txtBY;
    private javax.swing.JTextField txtEnterX;
    private javax.swing.JTextField txtEnterY;
    // End of variables declaration//GEN-END:variables
}
