/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rockpaperscissors;

import java.net.URL;
import javax.swing.Icon;
import javax.swing.ImageIcon;

/**
 *
 * @author 44869
 */
public class RockPaperScissors_GUI extends javax.swing.JFrame {

    /**
     * Creates new form RockPaperScissors_GUI
     */
    RockPaperScissors r;
    
    public RockPaperScissors_GUI() {
        initComponents();
        r = new RockPaperScissors();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblRock = new javax.swing.JPanel();
        lblComputer = new javax.swing.JLabel();
        lblPlayer = new javax.swing.JLabel();
        lblComputerIcon = new javax.swing.JLabel();
        lblPlayerIcon = new javax.swing.JLabel();
        btnRock = new javax.swing.JButton();
        btnPaper = new javax.swing.JButton();
        btnScissors = new javax.swing.JButton();
        lblComputerWins = new javax.swing.JLabel();
        lblDraws = new javax.swing.JLabel();
        lblPlayerWins = new javax.swing.JLabel();
        lblNumOfGames = new javax.swing.JLabel();
        txtComputerWins = new javax.swing.JTextField();
        txtDraws = new javax.swing.JTextField();
        txtPlayerWins = new javax.swing.JTextField();
        txtNumOfGames = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        lblPaper = new javax.swing.JLabel();
        lblScissors = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblComputer.setText("Computer");

        lblPlayer.setText("Player");

        lblComputerIcon.setBackground(new java.awt.Color(153, 255, 153));
        lblComputerIcon.setOpaque(true);

        lblPlayerIcon.setBackground(new java.awt.Color(204, 204, 255));
        lblPlayerIcon.setOpaque(true);

        btnRock.setBackground(       ImageIcon(getClass().getResource("/rockpaperscissors/image/1.png")););
        btnRock.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissors/image/rock_s.png"))); // NOI18N
        btnRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRockActionPerformed(evt);
            }
        });

        btnPaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissors/image/paper_s.png"))); // NOI18N
        btnPaper.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaperActionPerformed(evt);
            }
        });

        btnScissors.setIcon(new javax.swing.ImageIcon(getClass().getResource("/rockpaperscissors/image/scissors_s.png"))); // NOI18N
        btnScissors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnScissorsActionPerformed(evt);
            }
        });

        lblComputerWins.setText("Computer Wins");

        lblDraws.setText("Draws");

        lblPlayerWins.setText("Player Wins");

        lblNumOfGames.setText("Number Of Games");

        txtPlayerWins.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPlayerWinsActionPerformed(evt);
            }
        });

        jLabel7.setText("Rock");

        lblPaper.setText("Paper");

        lblScissors.setText("Scissors");

        javax.swing.GroupLayout lblRockLayout = new javax.swing.GroupLayout(lblRock);
        lblRock.setLayout(lblRockLayout);
        lblRockLayout.setHorizontalGroup(
            lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblRockLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblComputer)
                    .addComponent(lblComputerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPlayer)
                    .addComponent(lblPlayerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(138, 138, 138))
            .addGroup(lblRockLayout.createSequentialGroup()
                .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(lblRockLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(btnRock)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addGap(70, 70, 70)
                        .addComponent(btnPaper)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblPaper)
                        .addGap(87, 87, 87)
                        .addComponent(btnScissors)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblScissors))
                    .addGroup(lblRockLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblComputerWins)
                            .addComponent(lblDraws))
                        .addGap(53, 53, 53)
                        .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtDraws, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(txtComputerWins))
                        .addGap(76, 76, 76)
                        .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlayerWins)
                            .addComponent(lblNumOfGames))
                        .addGap(80, 80, 80)
                        .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtNumOfGames, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE)
                            .addComponent(txtPlayerWins))))
                .addContainerGap(79, Short.MAX_VALUE))
        );
        lblRockLayout.setVerticalGroup(
            lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblRockLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComputer)
                    .addComponent(lblPlayer))
                .addGap(18, 18, 18)
                .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComputerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPlayerIcon, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblRockLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(lblPaper)
                        .addGap(55, 55, 55))
                    .addGroup(lblRockLayout.createSequentialGroup()
                        .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblRockLayout.createSequentialGroup()
                                .addGap(38, 38, 38)
                                .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnPaper)
                                    .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(btnRock)
                                        .addComponent(btnScissors))))
                            .addGroup(lblRockLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(jLabel7))
                            .addGroup(lblRockLayout.createSequentialGroup()
                                .addGap(59, 59, 59)
                                .addComponent(lblScissors)))
                        .addGap(31, 31, 31)))
                .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblComputerWins)
                    .addComponent(lblPlayerWins)
                    .addComponent(txtComputerWins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtPlayerWins, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(lblRockLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDraws)
                    .addComponent(lblNumOfGames)
                    .addComponent(txtDraws, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumOfGames, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRockActionPerformed
        // TODO add your handling code here:
        lblPlayerIcon.setIcon(ImageIcon(getClass().getResource("/rockpaperscissors/image/rock.png")));
    }//GEN-LAST:event_btnRockActionPerformed

    private void txtPlayerWinsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPlayerWinsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPlayerWinsActionPerformed

    private void btnPaperActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaperActionPerformed
        // TODO add your handling code here:
        lblPlayerIcon.setIcon(ImageIcon(getClass().getResource("/rockpaperscissors/image/paper.png")));
    }//GEN-LAST:event_btnPaperActionPerformed

    private void btnScissorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnScissorsActionPerformed
        // TODO add your handling code here:
        lblPlayerIcon.setIcon(ImageIcon(getClass().getResource("/rockpaperscissors/image/scissors.png")));
    }//GEN-LAST:event_btnScissorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RockPaperScissors_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RockPaperScissors_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPaper;
    private javax.swing.JButton btnRock;
    private javax.swing.JButton btnScissors;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel lblComputer;
    private javax.swing.JLabel lblComputerIcon;
    private javax.swing.JLabel lblComputerWins;
    private javax.swing.JLabel lblDraws;
    private javax.swing.JLabel lblNumOfGames;
    private javax.swing.JLabel lblPaper;
    private javax.swing.JLabel lblPlayer;
    private javax.swing.JLabel lblPlayerIcon;
    private javax.swing.JLabel lblPlayerWins;
    private javax.swing.JPanel lblRock;
    private javax.swing.JLabel lblScissors;
    private javax.swing.JTextField txtComputerWins;
    private javax.swing.JTextField txtDraws;
    private javax.swing.JTextField txtNumOfGames;
    private javax.swing.JTextField txtPlayerWins;
    // End of variables declaration//GEN-END:variables

    private Icon ImageIcon(URL resource) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
